"use strict";

module.exports = {
    USERNAME: 1n,
    PLAYER_ID: 2n,
    STARS: 3n,
    DEMONS: 4n,
    // 5
    RELATIVE_POSITION: 6n,
    MATCHED: 7n,
    CP: 8n,
    ICON_ID: 9n,
    ICON_COLOR_1_ID: 10n,
    ICON_COLOR_2_ID: 11n,
    // 12
    SCOINS: 13n,
    GAMEMODE_ID: 14n,
    // 15
    ACCOUNT_ID: 16n,
    UCOINS: 17n,
    MESSAGE_FILTER_ID: 18n,
    FRIEND_REQUEST_FILTER_ID: 19n,
    YOUTUBE: 20n,
    CUBE_ID: 21n,
    SHIP_ID: 22n,
    BALL_ID: 23n,
    UFO_ID: 24n,
    DART_ID: 25n,
    ROBOT_ID: 26n,
    TRAIL_ID: 27n,
    GLOW: 28n,
    REGISTERED: 29n,
    RANK_GLOBAL: 30n,
    FRIEND_STATUS_ID: 31n,
    // 32
    // 33
    // 34
    FRIEND_REQUEST_MESSAGE: 35n,
    // 36
    FRIEND_REQUEST_TIMESTAMP: 37n,
    NEW_MESSAGES: 38n,
    NEW_FRIEND_REQUESTS: 39n,
    NEW_FRIENDS: 40n,
    // 41
    LEVEL_SCORE_TIMESTAMP: 42n,
    SPIDER_ID: 43n,
    TWITTER: 44n,
    TWITCH: 45n,
    DIAMONDS: 46n,
    // 47
    DEATH_EFFECT_ID: 48n,
    MOD_STATUS_ID: 49n,
    COMMENT_HISTORY_FILTER_ID: 50n
};